server:
  port: 9900
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: INFO

application.package: com.example.demo
website.name: https://google.com


spring:
  application:
    name: demo-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DEMODB
    username: root
    password: Psaiesh@21
    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
    
